/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ygpark2' at '16. 2. 17 오후 1:40' with Gradle 2.10
 *
 * @author ygpark2, @date 16. 2. 17 오후 1:40
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
