
import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertTrue;
import org.junit.jupiter.api.Test;

/*
 * This Java source file was auto generated by running 'gradle init --type java-library'
 * by 'ygpark2' at '16. 2. 17 오후 1:40' with Gradle 2.10
 *
 * @author ygpark2, @date 16. 2. 17 오후 1:40
 */
public class LibraryTest {

    @Test
    public void testSomeLibraryMethod() {
        Library classUnderTest = new Library();
        assertTrue(classUnderTest.someLibraryMethod(), "someLibraryMethod should return 'true'");
    }
}
